version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-hotel-search
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY:-your-qdrant-api-key}
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - app_network

  # Superlinked Backend Server
  superlinked-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: superlinked-backend
    container_name: superlinked-backend
    ports:
      - "8080:8080"
    environment:
      - TEXT_EMBEDDER_NAME=${TEXT_EMBEDDER_NAME:-sentence-transformers/all-mpnet-base-v2}
      - CHUNK_SIZE=${CHUNK_SIZE:-100}
      - PATH_CATEGORIES=${PATH_CATEGORIES:-https://storage.googleapis.com/superlinked-recipes-data/hotels-search/categories/categories.json}
      - PATH_DATASET=${PATH_DATASET:-https://storage.googleapis.com/superlinked-recipes-data/hotels-search/dataset/dataset.jsonl}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-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}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - QDRANT_API_KEY=${QDRANT_API_KEY:-your-qdrant-api-key}
    restart: unless-stopped
    depends_on:
      - qdrant
    networks:
      - app_network

  # Streamlit Frontend
  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlit-frontend
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    environment:
      - SUPERLINKED_API_URL=${SUPERLINKED_API_URL:-http://superlinked-backend:8080}
    restart: unless-stopped
    networks:
      - app_network

volumes:
  qdrant_storage:
    driver: local

networks:
  app_network:
    driver: bridge
